	platform :ios, '8.0'

target 'FrameWorksDemo' do
	use_frameworks!
	pod 'SDWebImage'		, '~> 4.0.0-beta2'
	pod 'FastImageCache'	, '~> 1.5.1'
	pod 'AFNetworking'		, '~> 3.1.0'
	pod 'AsyncDisplayKit'	, '~> 1.9.91'
	pod 'DTCoreText'		, '~> 1.6.19'
	pod 'ReactiveCocoa'		, '~> 4.2.2'
	pod 'ChameleonFramework', '~> 2.1.0'
	pod 'pop'				, '~> 1.0'
	#pod 'Spring'			, '~> 1.0.3'
end
